// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:136541823767:web:e67bc0106a88b6acc54d52',
    messagingSenderId: '136541823767',
    projectId: 'trip-planner-3dbeb',
    authDomain: 'trip-planner-3dbeb.firebaseapp.com',
    storageBucket: 'trip-planner-3dbeb.firebasestorage.app',
    measurementId: 'G-KQ37WEFMWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:136541823767:android:0183d1d164666047c54d52',
    messagingSenderId: '136541823767',
    projectId: 'trip-planner-3dbeb',
    storageBucket: 'trip-planner-3dbeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API_KEY_HERE',
    appId: '1:136541823767:ios:ab84f73e1f73e756c54d52',
    messagingSenderId: '136541823767',
    projectId: 'trip-planner-3dbeb',
    storageBucket: 'trip-planner-3dbeb.firebasestorage.app',
    iosBundleId: 'com.ismar.trip-planner',
  );
}
